# Generated by Django 4.2.2 on 2023-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
