# Generated by Django 4.2.2 on 2023-10-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_people_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='date',
        ),
    ]
